project_name: cre2
static_lib_name: libcre2.a
dyn_lib_name: libcre2.so
ban:
  ~ 
desc: Cre2 is the offical C language wrapper for RE2 the regular expressions library from Google.
extra_c_flags: 
  - -Wl,--start-group
  - /usr/local/lib/libabsl_debugging_internal.a
  - /usr/local/lib/libabsl_flags_usage.a
  - /usr/local/lib/libabsl_log_internal_fnmatch.a
  - /usr/local/lib/libabsl_random_internal_platform.a
  - /usr/local/lib/libabsl_strings.a
  - /usr/local/lib/libabsl_decode_rust_punycode.a
  - /usr/local/lib/libabsl_flags_usage_internal.a
  - /usr/local/lib/libabsl_log_internal_format.a
  - /usr/local/lib/libabsl_random_internal_randen.a
  - /usr/local/lib/libabsl_strings_internal.a
  - /usr/local/lib/libabsl_base.a
  - /usr/local/lib/libabsl_demangle_internal.a
  - /usr/local/lib/libabsl_generic_printer_internal.a
  - /usr/local/lib/libabsl_log_internal_globals.a
  - /usr/local/lib/libabsl_random_internal_randen_hwaes.a
  - /usr/local/lib/libabsl_symbolize.a
  - /usr/local/lib/libabsl_demangle_rust.a
  - /usr/local/lib/libabsl_graphcycles_internal.a
  - /usr/local/lib/libabsl_log_internal_log_sink_set.a
  - /usr/local/lib/libabsl_random_internal_randen_hwaes_impl.a
  - /usr/local/lib/libabsl_synchronization.a
  - /usr/local/lib/libabsl_city.a
  - /usr/local/lib/libabsl_die_if_null.a
  - /usr/local/lib/libabsl_hardening.a
  - /usr/local/lib/libabsl_log_internal_message.a
  - /usr/local/lib/libabsl_random_internal_randen_slow.a
  - /usr/local/lib/libabsl_throw_delegate.a
  - /usr/local/lib/libabsl_civil_time.a
  - /usr/local/lib/libabsl_examine_stack.a
  - /usr/local/lib/libabsl_hash.a
  - /usr/local/lib/libabsl_log_internal_nullguard.a
  - /usr/local/lib/libabsl_random_internal_seed_material.a
  - /usr/local/lib/libabsl_time.a
  - /usr/local/lib/libabsl_clock_interface.a
  - /usr/local/lib/libabsl_exponential_biased.a
  - /usr/local/lib/libabsl_hashtable_profiler.a
  - /usr/local/lib/libabsl_log_internal_proto.a
  - /usr/local/lib/libabsl_random_seed_gen_exception.a
  - /usr/local/lib/libabsl_time_zone.a
  - /usr/local/lib/libabsl_cord.a
  - /usr/local/lib/libabsl_failure_signal_handler.a
  - /usr/local/lib/libabsl_hashtablez_sampler.a
  - /usr/local/lib/libabsl_log_internal_structured_proto.a
  - /usr/local/lib/libabsl_random_seed_sequences.a
  - /usr/local/lib/libabsl_tracing_internal.a
  - /usr/local/lib/libabsl_cord_internal.a
  - /usr/local/lib/libabsl_flags_commandlineflag.a
  - /usr/local/lib/libabsl_int128.a
  - /usr/local/lib/libabsl_log_severity.a
  - /usr/local/lib/libabsl_raw_hash_set.a
  - /usr/local/lib/libabsl_utf8_for_code_point.a
  - /usr/local/lib/libabsl_cordz_functions.a
  - /usr/local/lib/libabsl_flags_commandlineflag_internal.a
  - /usr/local/lib/libabsl_kernel_timeout_internal.a
  - /usr/local/lib/libabsl_log_sink.a
  - /usr/local/lib/libabsl_raw_logging_internal.a
  - /usr/local/lib/libabsl_vlog_config_internal.a
  - /usr/local/lib/libabsl_cordz_handle.a
  - /usr/local/lib/libabsl_flags_config.a
  - /usr/local/lib/libabsl_leak_check.a
  - /usr/local/lib/libabsl_malloc_internal.a
  - /usr/local/lib/libabsl_scoped_set_env.a
  - /usr/local/lib/libabsl_cordz_info.a
  - /usr/local/lib/libabsl_flags_internal.a
  - /usr/local/lib/libabsl_log_entry.a
  - /usr/local/lib/libabsl_periodic_sampler.a
  - /usr/local/lib/libabsl_spinlock_wait.a
  - /usr/local/lib/libabsl_cordz_sample_token.a
  - /usr/local/lib/libabsl_flags_marshalling.a
  - /usr/local/lib/libabsl_log_flags.a
  - /usr/local/lib/libabsl_poison.a
  - /usr/local/lib/libabsl_stacktrace.a
  - /usr/local/lib/libabsl_crc32c.a
  - /usr/local/lib/libabsl_flags_parse.a
  - /usr/local/lib/libabsl_log_globals.a
  - /usr/local/lib/libabsl_profile_builder.a
  - /usr/local/lib/libabsl_status.a
  - /usr/local/lib/libabsl_crc_cord_state.a
  - /usr/local/lib/libabsl_flags_private_handle_accessor.a
  - /usr/local/lib/libabsl_log_initialize.a
  - /usr/local/lib/libabsl_random_distributions.a
  - /usr/local/lib/libabsl_statusor.a
  - /usr/local/lib/libabsl_crc_cpu_detect.a
  - /usr/local/lib/libabsl_flags_program_name.a
  - /usr/local/lib/libabsl_log_internal_check_op.a
  - /usr/local/lib/libabsl_random_internal_distribution_test_util.a
  - /usr/local/lib/libabsl_str_format_internal.a
  - /usr/local/lib/libabsl_crc_internal.a
  - /usr/local/lib/libabsl_flags_reflection.a
  - /usr/local/lib/libabsl_log_internal_conditions.a
  - /usr/local/lib/libabsl_random_internal_entropy_pool.a
  - /usr/local/lib/libabsl_strerror.a
  - -Wl,--end-group
